{"level":"\u001b[31merror\u001b[39m","message":"Uncaught Exception: Route.post() requires a callback function but got a [object Undefined]","service":"finance-management-system","stack":"Error: Route.post() requires a callback function but got a [object Undefined]\n    at Route.<computed> [as post] (D:\\final-cloud-fms\\cloud-based-finance-management-system\\backend\\node_modules\\express\\lib\\router\\route.js:211:15)\n    at proto.<computed> [as post] (D:\\final-cloud-fms\\cloud-based-finance-management-system\\backend\\node_modules\\express\\lib\\router\\index.js:521:19)\n    at Object.<anonymous> (D:\\final-cloud-fms\\cloud-based-finance-management-system\\backend\\routes\\auth.js:51:8)\n    at Module._compile (node:internal/modules/cjs/loader:1730:14)\n    at Object..js (node:internal/modules/cjs/loader:1895:10)\n    at Module.load (node:internal/modules/cjs/loader:1465:32)\n    at Function._load (node:internal/modules/cjs/loader:1282:12)\n    at TracingChannel.traceSync (node:diagnostics_channel:322:14)\n    at wrapModuleLoad (node:internal/modules/cjs/loader:235:24)\n    at Module.require (node:internal/modules/cjs/loader:1487:12)","timestamp":"2025-06-19 23:08:14"}
{"level":"\u001b[31merror\u001b[39m","message":"Uncaught Exception: Route.post() requires a callback function but got a [object Undefined]","service":"finance-management-system","stack":"Error: Route.post() requires a callback function but got a [object Undefined]\n    at Route.<computed> [as post] (D:\\final-cloud-fms\\cloud-based-finance-management-system\\backend\\node_modules\\express\\lib\\router\\route.js:211:15)\n    at proto.<computed> [as post] (D:\\final-cloud-fms\\cloud-based-finance-management-system\\backend\\node_modules\\express\\lib\\router\\index.js:521:19)\n    at Object.<anonymous> (D:\\final-cloud-fms\\cloud-based-finance-management-system\\backend\\routes\\auth.js:51:8)\n    at Module._compile (node:internal/modules/cjs/loader:1730:14)\n    at Object..js (node:internal/modules/cjs/loader:1895:10)\n    at Module.load (node:internal/modules/cjs/loader:1465:32)\n    at Function._load (node:internal/modules/cjs/loader:1282:12)\n    at TracingChannel.traceSync (node:diagnostics_channel:322:14)\n    at wrapModuleLoad (node:internal/modules/cjs/loader:235:24)\n    at Module.require (node:internal/modules/cjs/loader:1487:12)","timestamp":"2025-06-19 23:09:45"}
{"level":"\u001b[31merror\u001b[39m","message":"Uncaught Exception: Route.get() requires a callback function but got a [object Undefined]","service":"finance-management-system","stack":"Error: Route.get() requires a callback function but got a [object Undefined]\n    at Route.<computed> [as get] (D:\\final-cloud-fms\\cloud-based-finance-management-system\\backend\\node_modules\\express\\lib\\router\\route.js:211:15)\n    at Object.<anonymous> (D:\\final-cloud-fms\\cloud-based-finance-management-system\\backend\\routes\\users.js:38:4)\n    at Module._compile (node:internal/modules/cjs/loader:1730:14)\n    at Object..js (node:internal/modules/cjs/loader:1895:10)\n    at Module.load (node:internal/modules/cjs/loader:1465:32)\n    at Function._load (node:internal/modules/cjs/loader:1282:12)\n    at TracingChannel.traceSync (node:diagnostics_channel:322:14)\n    at wrapModuleLoad (node:internal/modules/cjs/loader:235:24)\n    at Module.require (node:internal/modules/cjs/loader:1487:12)\n    at require (node:internal/modules/helpers:135:16)","timestamp":"2025-06-19 23:12:23"}
{"level":"\u001b[31merror\u001b[39m","message":"Uncaught Exception: Route.get() requires a callback function but got a [object Undefined]","service":"finance-management-system","stack":"Error: Route.get() requires a callback function but got a [object Undefined]\n    at Route.<computed> [as get] (D:\\final-cloud-fms\\cloud-based-finance-management-system\\backend\\node_modules\\express\\lib\\router\\route.js:211:15)\n    at Object.<anonymous> (D:\\final-cloud-fms\\cloud-based-finance-management-system\\backend\\routes\\users.js:38:4)\n    at Module._compile (node:internal/modules/cjs/loader:1730:14)\n    at Object..js (node:internal/modules/cjs/loader:1895:10)\n    at Module.load (node:internal/modules/cjs/loader:1465:32)\n    at Function._load (node:internal/modules/cjs/loader:1282:12)\n    at TracingChannel.traceSync (node:diagnostics_channel:322:14)\n    at wrapModuleLoad (node:internal/modules/cjs/loader:235:24)\n    at Module.require (node:internal/modules/cjs/loader:1487:12)\n    at require (node:internal/modules/helpers:135:16)","timestamp":"2025-06-19 23:12:49"}
{"level":"\u001b[31merror\u001b[39m","message":"Uncaught Exception: Route.get() requires a callback function but got a [object Undefined]","service":"finance-management-system","stack":"Error: Route.get() requires a callback function but got a [object Undefined]\n    at Route.<computed> [as get] (D:\\final-cloud-fms\\cloud-based-finance-management-system\\backend\\node_modules\\express\\lib\\router\\route.js:211:15)\n    at Object.<anonymous> (D:\\final-cloud-fms\\cloud-based-finance-management-system\\backend\\routes\\users.js:46:4)\n    at Module._compile (node:internal/modules/cjs/loader:1730:14)\n    at Object..js (node:internal/modules/cjs/loader:1895:10)\n    at Module.load (node:internal/modules/cjs/loader:1465:32)\n    at Function._load (node:internal/modules/cjs/loader:1282:12)\n    at TracingChannel.traceSync (node:diagnostics_channel:322:14)\n    at wrapModuleLoad (node:internal/modules/cjs/loader:235:24)\n    at Module.require (node:internal/modules/cjs/loader:1487:12)\n    at require (node:internal/modules/helpers:135:16)","timestamp":"2025-06-19 23:18:05"}
{"level":"\u001b[31merror\u001b[39m","message":"Uncaught Exception: Route.get() requires a callback function but got a [object Undefined]","service":"finance-management-system","stack":"Error: Route.get() requires a callback function but got a [object Undefined]\n    at Route.<computed> [as get] (D:\\final-cloud-fms\\cloud-based-finance-management-system\\backend\\node_modules\\express\\lib\\router\\route.js:211:15)\n    at Object.<anonymous> (D:\\final-cloud-fms\\cloud-based-finance-management-system\\backend\\routes\\users.js:46:4)\n    at Module._compile (node:internal/modules/cjs/loader:1730:14)\n    at Object..js (node:internal/modules/cjs/loader:1895:10)\n    at Module.load (node:internal/modules/cjs/loader:1465:32)\n    at Function._load (node:internal/modules/cjs/loader:1282:12)\n    at TracingChannel.traceSync (node:diagnostics_channel:322:14)\n    at wrapModuleLoad (node:internal/modules/cjs/loader:235:24)\n    at Module.require (node:internal/modules/cjs/loader:1487:12)\n    at require (node:internal/modules/helpers:135:16)","timestamp":"2025-06-19 23:21:59"}
{"level":"\u001b[31merror\u001b[39m","message":"Uncaught Exception: Route.get() requires a callback function but got a [object Undefined]","service":"finance-management-system","stack":"Error: Route.get() requires a callback function but got a [object Undefined]\n    at Route.<computed> [as get] (D:\\final-cloud-fms\\cloud-based-finance-management-system\\backend\\node_modules\\express\\lib\\router\\route.js:211:15)\n    at Object.<anonymous> (D:\\final-cloud-fms\\cloud-based-finance-management-system\\backend\\routes\\users.js:47:4)\n    at Module._compile (node:internal/modules/cjs/loader:1730:14)\n    at Object..js (node:internal/modules/cjs/loader:1895:10)\n    at Module.load (node:internal/modules/cjs/loader:1465:32)\n    at Function._load (node:internal/modules/cjs/loader:1282:12)\n    at TracingChannel.traceSync (node:diagnostics_channel:322:14)\n    at wrapModuleLoad (node:internal/modules/cjs/loader:235:24)\n    at Module.require (node:internal/modules/cjs/loader:1487:12)\n    at require (node:internal/modules/helpers:135:16)","timestamp":"2025-06-19 23:24:39"}
{"level":"\u001b[31merror\u001b[39m","message":"Uncaught Exception: Route.get() requires a callback function but got a [object Undefined]","service":"finance-management-system","stack":"Error: Route.get() requires a callback function but got a [object Undefined]\n    at Route.<computed> [as get] (D:\\final-cloud-fms\\cloud-based-finance-management-system\\backend\\node_modules\\express\\lib\\router\\route.js:211:15)\n    at proto.<computed> [as get] (D:\\final-cloud-fms\\cloud-based-finance-management-system\\backend\\node_modules\\express\\lib\\router\\index.js:521:19)\n    at Object.<anonymous> (D:\\final-cloud-fms\\cloud-based-finance-management-system\\backend\\routes\\users.js:37:8)\n    at Module._compile (node:internal/modules/cjs/loader:1730:14)\n    at Object..js (node:internal/modules/cjs/loader:1895:10)\n    at Module.load (node:internal/modules/cjs/loader:1465:32)\n    at Function._load (node:internal/modules/cjs/loader:1282:12)\n    at TracingChannel.traceSync (node:diagnostics_channel:322:14)\n    at wrapModuleLoad (node:internal/modules/cjs/loader:235:24)\n    at Module.require (node:internal/modules/cjs/loader:1487:12)","timestamp":"2025-06-19 23:26:36"}
{"level":"\u001b[31merror\u001b[39m","message":"Uncaught Exception: Route.get() requires a callback function but got a [object Undefined]","service":"finance-management-system","stack":"Error: Route.get() requires a callback function but got a [object Undefined]\n    at Route.<computed> [as get] (D:\\final-cloud-fms\\cloud-based-finance-management-system\\backend\\node_modules\\express\\lib\\router\\route.js:211:15)\n    at proto.<computed> [as get] (D:\\final-cloud-fms\\cloud-based-finance-management-system\\backend\\node_modules\\express\\lib\\router\\index.js:521:19)\n    at Object.<anonymous> (D:\\final-cloud-fms\\cloud-based-finance-management-system\\backend\\routes\\users.js:37:8)\n    at Module._compile (node:internal/modules/cjs/loader:1730:14)\n    at Object..js (node:internal/modules/cjs/loader:1895:10)\n    at Module.load (node:internal/modules/cjs/loader:1465:32)\n    at Function._load (node:internal/modules/cjs/loader:1282:12)\n    at TracingChannel.traceSync (node:diagnostics_channel:322:14)\n    at wrapModuleLoad (node:internal/modules/cjs/loader:235:24)\n    at Module.require (node:internal/modules/cjs/loader:1487:12)","timestamp":"2025-06-19 23:26:43"}
{"level":"\u001b[31merror\u001b[39m","message":"Uncaught Exception: errors is not defined","service":"finance-management-system","stack":"ReferenceError: errors is not defined\n    at Object.<anonymous> (D:\\final-cloud-fms\\cloud-based-finance-management-system\\backend\\server.js:170:5)\n    at Module._compile (node:internal/modules/cjs/loader:1730:14)\n    at Object..js (node:internal/modules/cjs/loader:1895:10)\n    at Module.load (node:internal/modules/cjs/loader:1465:32)\n    at Function._load (node:internal/modules/cjs/loader:1282:12)\n    at TracingChannel.traceSync (node:diagnostics_channel:322:14)\n    at wrapModuleLoad (node:internal/modules/cjs/loader:235:24)\n    at Function.executeUserEntryPoint [as runMain] (node:internal/modules/run_main:171:5)\n    at node:internal/main/run_main_module:36:49","timestamp":"2025-06-19 23:30:30"}
{"level":"\u001b[31merror\u001b[39m","message":"Uncaught Exception: errors is not defined","service":"finance-management-system","stack":"ReferenceError: errors is not defined\n    at Object.<anonymous> (D:\\final-cloud-fms\\cloud-based-finance-management-system\\backend\\server.js:170:5)\n    at Module._compile (node:internal/modules/cjs/loader:1730:14)\n    at Object..js (node:internal/modules/cjs/loader:1895:10)\n    at Module.load (node:internal/modules/cjs/loader:1465:32)\n    at Function._load (node:internal/modules/cjs/loader:1282:12)\n    at TracingChannel.traceSync (node:diagnostics_channel:322:14)\n    at wrapModuleLoad (node:internal/modules/cjs/loader:235:24)\n    at Function.executeUserEntryPoint [as runMain] (node:internal/modules/run_main:171:5)\n    at node:internal/main/run_main_module:36:49","timestamp":"2025-06-19 23:32:07"}
{"level":"\u001b[32minfo\u001b[39m","message":"\n======================================================================","service":"finance-management-system","timestamp":"2025-06-19 23:41:04"}
{"level":"\u001b[32minfo\u001b[39m","message":"\u001b[1m\u001b[32m🚀 Server running in development mode\u001b[39m\u001b[22m","service":"finance-management-system","timestamp":"2025-06-19 23:41:04"}
{"level":"\u001b[32minfo\u001b[39m","message":"\u001b[4m\u001b[36m🌐 Access the server at: http://0.0.0.0:5000\u001b[39m\u001b[24m","service":"finance-management-system","timestamp":"2025-06-19 23:41:04"}
{"level":"\u001b[32minfo\u001b[39m","message":"\u001b[4m\u001b[36m📊 API Documentation: http://0.0.0.0:5000/api-docs\u001b[39m\u001b[24m","service":"finance-management-system","timestamp":"2025-06-19 23:41:04"}
{"level":"\u001b[32minfo\u001b[39m","message":"\u001b[4m\u001b[36m📈 Health Check: http://0.0.0.0:5000/api/v1/health\u001b[39m\u001b[24m","service":"finance-management-system","timestamp":"2025-06-19 23:41:04"}
{"level":"\u001b[32minfo\u001b[39m","message":"======================================================================\n","service":"finance-management-system","timestamp":"2025-06-19 23:41:04"}
{"address":"0.0.0.0","code":"EADDRINUSE","errno":-4091,"level":"\u001b[31merror\u001b[39m","message":"Uncaught Exception: listen EADDRINUSE: address already in use 0.0.0.0:5000","port":5000,"service":"finance-management-system","stack":"Error: listen EADDRINUSE: address already in use 0.0.0.0:5000\n    at Server.setupListenHandle [as _listen2] (node:net:1939:16)\n    at listenInCluster (node:net:1996:12)\n    at node:net:2205:7\n    at process.processTicksAndRejections (node:internal/process/task_queues:90:21)","syscall":"listen","timestamp":"2025-06-19 23:42:57"}
{"address":"0.0.0.0","code":"EADDRINUSE","errno":-4091,"level":"\u001b[31merror\u001b[39m","message":"Uncaught Exception: listen EADDRINUSE: address already in use 0.0.0.0:5000","port":5000,"service":"finance-management-system","stack":"Error: listen EADDRINUSE: address already in use 0.0.0.0:5000\n    at Server.setupListenHandle [as _listen2] (node:net:1939:16)\n    at listenInCluster (node:net:1996:12)\n    at node:net:2205:7\n    at process.processTicksAndRejections (node:internal/process/task_queues:90:21)","syscall":"listen","timestamp":"2025-06-19 23:42:57"}
{"level":"\u001b[32minfo\u001b[39m","message":"Process exiting with code 0","service":"finance-management-system","timestamp":"2025-06-19 23:42:57"}
{"level":"\u001b[32minfo\u001b[39m","message":"\n======================================================================","service":"finance-management-system","timestamp":"2025-06-19 23:45:15"}
{"level":"\u001b[32minfo\u001b[39m","message":"\u001b[1m\u001b[32m🚀 Server running in development mode\u001b[39m\u001b[22m","service":"finance-management-system","timestamp":"2025-06-19 23:45:15"}
{"level":"\u001b[32minfo\u001b[39m","message":"\u001b[4m\u001b[36m🌐 Access the server at: http://0.0.0.0:5000\u001b[39m\u001b[24m","service":"finance-management-system","timestamp":"2025-06-19 23:45:15"}
{"level":"\u001b[32minfo\u001b[39m","message":"\u001b[4m\u001b[36m📊 API Documentation: http://0.0.0.0:5000/api-docs\u001b[39m\u001b[24m","service":"finance-management-system","timestamp":"2025-06-19 23:45:15"}
{"level":"\u001b[32minfo\u001b[39m","message":"\u001b[4m\u001b[36m📈 Health Check: http://0.0.0.0:5000/api/v1/health\u001b[39m\u001b[24m","service":"finance-management-system","timestamp":"2025-06-19 23:45:15"}
{"level":"\u001b[32minfo\u001b[39m","message":"======================================================================\n","service":"finance-management-system","timestamp":"2025-06-19 23:45:15"}
{"address":"0.0.0.0","code":"EADDRINUSE","errno":-4091,"level":"\u001b[31merror\u001b[39m","message":"Uncaught Exception: listen EADDRINUSE: address already in use 0.0.0.0:5000","port":5000,"service":"finance-management-system","stack":"Error: listen EADDRINUSE: address already in use 0.0.0.0:5000\n    at Server.setupListenHandle [as _listen2] (node:net:1939:16)\n    at listenInCluster (node:net:1996:12)\n    at node:net:2205:7\n    at process.processTicksAndRejections (node:internal/process/task_queues:90:21)","syscall":"listen","timestamp":"2025-06-19 23:45:55"}
{"address":"0.0.0.0","code":"EADDRINUSE","errno":-4091,"level":"\u001b[31merror\u001b[39m","message":"Uncaught Exception: listen EADDRINUSE: address already in use 0.0.0.0:5000","port":5000,"service":"finance-management-system","stack":"Error: listen EADDRINUSE: address already in use 0.0.0.0:5000\n    at Server.setupListenHandle [as _listen2] (node:net:1939:16)\n    at listenInCluster (node:net:1996:12)\n    at node:net:2205:7\n    at process.processTicksAndRejections (node:internal/process/task_queues:90:21)","syscall":"listen","timestamp":"2025-06-19 23:45:55"}
{"level":"\u001b[32minfo\u001b[39m","message":"Process exiting with code 0","service":"finance-management-system","timestamp":"2025-06-19 23:45:55"}
{"level":"\u001b[32minfo\u001b[39m","message":"\n======================================================================","service":"finance-management-system","timestamp":"2025-06-19 23:50:29"}
{"level":"\u001b[32minfo\u001b[39m","message":"\u001b[1m\u001b[32m🚀 Server running in development mode\u001b[39m\u001b[22m","service":"finance-management-system","timestamp":"2025-06-19 23:50:29"}
{"level":"\u001b[32minfo\u001b[39m","message":"\u001b[4m\u001b[36m🌐 Access the server at: http://0.0.0.0:5000\u001b[39m\u001b[24m","service":"finance-management-system","timestamp":"2025-06-19 23:50:29"}
{"level":"\u001b[32minfo\u001b[39m","message":"\u001b[4m\u001b[36m📊 API Documentation: http://0.0.0.0:5000/api-docs\u001b[39m\u001b[24m","service":"finance-management-system","timestamp":"2025-06-19 23:50:29"}
{"level":"\u001b[32minfo\u001b[39m","message":"\u001b[4m\u001b[36m📈 Health Check: http://0.0.0.0:5000/api/v1/health\u001b[39m\u001b[24m","service":"finance-management-system","timestamp":"2025-06-19 23:50:29"}
{"level":"\u001b[32minfo\u001b[39m","message":"======================================================================\n","service":"finance-management-system","timestamp":"2025-06-19 23:50:29"}
